import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
@ComponentScan("book")
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
